# Generated by Django 2.2.14 on 2021-12-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SU', 'Chống nắng'), ('SK', 'Chăm sóc da'), ('HA', 'Dưỡng tóc'), ('BO', 'Chăm sóc cơ thể'), ('PF', 'Nước hoa'), ('DC', 'Mỹ phẩm trang điểm'), ('OR', 'Chăm sóc miệng')], max_length=2),
        ),
    ]
